### ISSUE TITLE
Compilation Error: undefined symbol: log-2

### ISSUE THREAD

**Issue by retsyo** [ldci/redCV#7]
I am using the latest red from master branch, which is downloaded from https://www.red-lang.org/p/download.html, on windows 10. however
```
r:\>red-22sep20-9648d6137.exe -u -c -r redCV-master\samples\image_transformation\ImageClip.red

-=== Red Compiler 0.6.4 ===-

Compiling r:\redCV-master\samples\image_transformation\ImageClip.red ...
...compilation time : 2578 ms

Target: MSDOS

Compiling to native code...
*** Compilation Error: undefined symbol: log-2
*** in file: %/r/redCV-master/libs/tools/rcvTools.red
*** in function: exec/rcvLog-2
*** at line: 2674
*** near: (log-2 value)

```

**Comment by ldci** [comment]
Hi
Your problem is related to a recent change in Red/S for log functions
Edit /libs/tools/rcvTools.red and replace rcvLog-2 routine

By this new one

rcvLog-2: routine [
"Return the base-2 logarithm"
value [float!]
return: [float!]
][
(log-e value) / 0.6931471805599453
]

Regards


[cid:image001.png@01D41D15.0B4818A0]




[cid:image002.png@01D41D15.0B4818A0]

François Jouen
École Pratique des Hautes Études
Doyen de la section des Sciences de la Vie et de la Terre
Chaire Psychobiologie du Développement
Laboratoire Cognitions Humaine et Artificielle (CHArt) EA 4004 FED 4246
Patios Saint-Jacques
4-14, rue Ferrus - 75014 Paris
01 53 63 61 64 / 06 87 13 76 81
francois.jouen@ephe.psl.eu<mailto:francois.jouen@ephe.psl.eu>
www.ephe.fr<http://www.ephe.fr>

Le 23 sept. 2020 à 03:46, retsyo <notifications@github.com<mailto:notifications@github.com>> a écrit :



I am using the latest red from master branch, which is downloaded from https://www.red-lang.org/p/download.html, on windows 10. however

r:\>red-22sep20-9648d6137.exe -u -c -r redCV-master\samples\image_transformation\ImageClip.red

-=== Red Compiler 0.6.4 ===-

Compiling r:\redCV-master\samples\image_transformation\ImageClip.red ...
...compilation time : 2578 ms

Target: MSDOS

Compiling to native code...
*** Compilation Error: undefined symbol: log-2
*** in file: %/r/redCV-master/libs/tools/rcvTools.red
*** in function: exec/rcvLog-2
*** at line: 2674
*** near: (log-2 value)
